# permissions for end users to view periodiccurls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: periodiccurl-viewer-role
rules:
- apiGroups:
  - jobs.amir.job
  resources:
  - periodiccurls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobs.amir.job
  resources:
  - periodiccurls/status
  verbs:
  - get
