# permissions for end users to edit periodiccurls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: periodiccurl-editor-role
rules:
- apiGroups:
  - jobs.amir.job
  resources:
  - periodiccurls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.amir.job
  resources:
  - periodiccurls/status
  verbs:
  - get
